import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { MemberProvider } from "@/contexts/member-context";
import { OrderProvider } from "@/contexts/order-context";
import { DishesProvider } from "@/contexts/dishes-context";
import { PageProtectorProvider } from "@/contexts/page-protector-context";

const promptFont = Prompt({
  subsets: ["thai", "latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${promptFont.className} scrollbar-hide select-none antialiased`}
      >
        <MemberProvider>
          <OrderProvider>
            <DishesProvider>
              <PageProtectorProvider>
                {children}
              </PageProtectorProvider>
            </DishesProvider>
          </OrderProvider>
        </MemberProvider>
      </body>
    </html>
  );
}